type Query {
  items: [Item!]!
  item(id: ID!): Item
}

type Item {
  id: ID!
  name: String!
  address: String!
  status: String!
}

type Mutation {
  addItem(name: String!, address: String!, status: String!): Item!
  updateItem(id: ID!, name: String, address: String, status: String): Item!
  deleteItem(id: ID!): Item!
}